version: "3.2"

services:

  adegasapi:
    container_name: adegasapi
    image: adegasapi
    networks:
      - default_network
    ports:
      - 8020:8020
    environment:
      MONGO_URL_STRING_CONNECTION: <URI>
      MONGO_DATABASE: <NAME>

networks:
  default_network:
    driver: bridge